# Generated by Django 4.0.5 on 2022-06-16 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_add_user_provider_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Service Area Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Service Area Price')),
                ('geo_json', models.JSONField(verbose_name='Polygon coordinates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='providers.provider')),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'db_table': 'service_areas',
                'ordering': ('name', 'provider'),
            },
        ),
    ]
