# Generated by Django 4.0.5 on 2022-06-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_add_service_area_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='geo_json',
            field=models.TextField(max_length=1000, verbose_name='Polygon coordinates'),
        ),
    ]
