# Generated by Django 4.0.5 on 2022-06-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_geo_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(editable=False, max_length=255, verbose_name='Provider Email'),
        ),
    ]
